repos:
  - repo: https://github.com/pre-commit/mirrors-shellcheck
    rev: v0.9.0  # Remplace par la dernière version stable si besoin
    hooks:
      - id: shellcheck
        files: \.sh$

  - repo: https://github.com/mvdan/sh
    rev: v3.7.0  # Version de shfmt
    hooks:
      - id: shfmt
        files: \.sh$
        args: ["-i", "2", "-ci"]
